In [ ]:
# 1. Convert List to 1D Array
# Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

# Expected Output:

# Original List: [12.23, 13.32, 100, 36.32] One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [1]:
import numpy as np

In [13]:

ls = [12.23, 13.32, 100, 36.32]
a = np.array(ls)
a

array([ 12.23,  13.32, 100.  ,  36.32])

In [ ]:
# 2. Create 3x3 Matrix (2?10)
# Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

# Expected Output:

# [[ 2 3 4] [ 5 6 7] [ 8 9 10]]

In [18]:
a = np.arange(2, 11)
matrix = a.reshape(3,3)
matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [20]:
matrix = np.arange(2, 11).reshape(3,3)
matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [26]:
# 3. Null Vector (10) & Update Sixth Value
# Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

# [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

# Update sixth value to 11 [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]


vector = np.zeros(10)
vector[6] = 11
print(vector)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [ ]:
# 4. Array from 12 to 38
# Write a NumPy program to create an array with values ranging from 12 to 38.

# Expected Output:

# [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [29]:
a = np.arange(12,38)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [ ]:
# 5. Convert Array to Float Type
# Write a NumPy program to convert an array to a floating type.

# Sample output:

# Original array [1, 2, 3, 4]

In [33]:
a = np.array([1, 2, 3, 4])
b = a.astype(float)
b

array([1., 2., 3., 4.])

In [ ]:
# 6. Celsius to Fahrenheit Conversion
# Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.

# Sample Array [0, 12, 45.21, 34, 99.91] [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]

# Expected Output:

# Values in Fahrenheit degrees: [ 0. 12. 45.21 34. 99.91 32. ]

# Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]

# Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]

# Values in Fahrenheit degrees: [-0. 12. 45.21 34. 99.91 32. ]

In [34]:
import numpy as np


celsius_values = np.array([0, 12, 45.21, 34, 99.91])


fahrenheit_values = (celsius_values * 9/5) + 32

print("Values in Centigrade degrees:", celsius_values)
print("Values in Fahrenheit degrees:", fahrenheit_values)


Values in Centigrade degrees: [ 0.   12.   45.21 34.   99.91]
Values in Fahrenheit degrees: [ 32.     53.6   113.378  93.2   211.838]


In [61]:
# 7. Append Values to Array (Do self-tudy)
# Write a NumPy program to append values to the end of an array.

# Expected Output:

# Original array: [10, 20, 30]

# After append values to the end of the array: [10 20 30 40 50 60 70 80 90]

array = [10, 20, 30]
b = [40, 50, 60, 70, 80, 90]
array = np.append(array, b)
array

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
# 8. Array Statistical Functions (Do self-tudy)
# Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array.
import numpy as np
array = np.random.random((10))
median_val = np.median(array)
std_val = array.std()
print("\nMean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)


Mean: 0.6880913510856282
Median: 0.46337919443642056
Standard Deviation: 0.29895523673047675


In [43]:
# 9 Find min and max
# Create a 10x10 array with random values and find the minimum and maximum values.

array = np.random.random((10,10))
min_val = array.min()
max_val = array.max()
print(min_val, max_val)

0.0002031304187457561 0.9954605059105361


In [ ]:
# 10
# Create a 3x3x3 array with random values.

In [35]:
array = np.random.random((3, 3, 3))

print(array)

[[[0.07217738 0.77314196 0.25898687]
  [0.61576018 0.62924073 0.33812599]
  [0.42028495 0.4012019  0.00868816]]

 [[0.84733162 0.24977037 0.73083104]
  [0.12447727 0.78113463 0.93505164]
  [0.3398015  0.13284061 0.42866524]]

 [[0.53070055 0.83645376 0.8697712 ]
  [0.8633823  0.86293809 0.6119591 ]
  [0.46117758 0.4267626  0.934429  ]]]
